name: 'Close stale issues'
on:
  schedule:
    - cron: '29 1 * * *'
  workflow_dispatch:
  
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 120
        days-before-close: 0
        any-of-labels: 'SDK Release,Documentation,Breaking Change,SDK Deprecated'
